---
- name: ETCD | Copy ETCD Server cert config files
  template:
    src: "etcd-server-csr.json.j2"
    dest: "{{ etcd_cert_dir }}/etcd-server-csr.json"
    mode: "0644"
  register: etcd_server_conf

- name: ETCD | Check that ETCD Server cert exists
  stat:
    path: "{{ etcd_cert_dir }}/server-key.pem"
  register: _etcd_server_cert

- name: ETCD | Generatting ETCD Server cert
  shell: >-
    {{ cfssl_bin_path }}/cfssl gencert
    -ca={{ etcd_cert_dir }}/etcd-ca.pem
    -ca-key={{ etcd_cert_dir }}/etcd-ca-key.pem
    -config={{ etcd_cert_dir }}/etcd-cfssl-config.json
    -profile=peer {{ etcd_cert_dir }}/etcd-server-csr.json | {{ cfssl_bin_path }}/cfssljson -bare {{ etcd_cert_dir }}/server
  when:
    - not _etcd_server_cert.stat.exists or
      etcd_server_conf.changed or
      etcd_ca.changed|default(false)
  register: etcd_server_cert
