---
- name: ETCD | Copy ETCD healthcheck cert config files
  template:
    src: "etcd-healthcheck-client-csr.json.j2"
    dest: "{{ etcd_cert_dir }}/etcd-healthcheck-client-csr.json"
    mode: "0644"
  register: etcd_healthcheck_conf

- name: ETCD | Check that ETCD Peer cert exists
  stat:
    path: "{{ etcd_cert_dir }}/etcd-healthcheck-client-key.pem"
  register: etcd_healthcheck_cert

- name: ETCD | Generatting ETCD healthcheck cert
  shell: >-
    {{ cfssl_bin_path }}/cfssl gencert
    -ca={{ etcd_cert_dir }}/etcd-ca.pem
    -ca-key={{ etcd_cert_dir }}/etcd-ca-key.pem
    -config={{ etcd_cert_dir }}/etcd-cfssl-config.json
    -profile=client {{ etcd_cert_dir }}/etcd-healthcheck-client-csr.json | {{ cfssl_bin_path }}/cfssljson -bare {{ etcd_cert_dir }}/etcd-healthcheck-client
  when:
    - not etcd_healthcheck_cert.stat.exists or
      etcd_healthcheck_conf.changed or
      etcd_ca.changed|default(false)
