---
- name: ETCD | Slurp ETCD CA certs
  slurp:
    src: "{{ item }}"
  loop:
    - "{{ etcd_ca_cert_file }}"
    - "{{ etcd_ca_key_file }}"
  register: etcd_ca_certs
  delegate_to: "{{ groups[etcd_group_name][0] }}"
  run_once: true

- name: ETCD | Write out ETCD CA certs
  copy:
    dest: "{{ item.item }}"
    content: "{{ item.content | b64decode }}"
    owner: "{{ etcd_user_name }}"
    group: "{{ etcd_user_group }}"
    mode: "0600"
  no_log: true
  register: etcd_ca
  loop: "{{ etcd_ca_certs.results }}"
  when: inventory_hostname != groups[etcd_group_name][0]
