---
- name: ETCD |(when cert_provider == cfssl)
  block:
    - name: ETCD | Copy ETCD CA cert config files
      template:
        src: "etcd-ca-csr.json.j2"
        dest: "{{ etcd_cert_dir }}/etcd-ca-csr.json"
        owner: "{{ etcd_user }}"
        group: "{{ etcd_group }}"
        mode: "0644"
      register: etcd_ca_conf

    - name: ETCD | Check that ETCD CA cert exists
      stat:
        path: "{{ etcd_cert_dir }}/etcd-ca-key.pem"
      register: etcd_ca_cert

    - name: ETCD | Generatting ETCD CA cert
      shell: >-
        {{ cfssl_bin_path }}/cfssl genkey 
        -initca {{ etcd_cert_dir }}/etcd-ca-csr.json | {{ cfssl_bin_path }}/cfssljson 
        -bare {{ etcd_cert_dir }}/etcd-ca
      when:
        - not etcd_ca_cert.stat.exists or
          etcd_ca_conf.changed
      notify: ETCD | Set 'etcd_ca_changed' to true
  when: cert_provider == 'cfssl'

- name: ETCD |(when cert_provider == ssl)
  block:
    - name: ETCD | Generate an OpenSSL private CA key
      openssl_privatekey:
        path: "{{ etcd_cert_dir }}/etcd-ca-key.pem"
        owner: "{{ etcd_user }}"
        group: "{{ etcd_group }}"
        type: RSA
        size: "{{ ca_certificates_key_size }}"

    - name: ETCD | Generate an OpenSSL Certificate Signing Request for CA certificate
      openssl_csr:
        path: "{{ etcd_cert_dir }}/etcd-ca.csr"
        owner: "{{ etcd_user }}"
        group: "{{ etcd_group }}"
        privatekey_path: "{{ etcd_cert_dir }}/etcd-ca-key.pem"
        common_name: etcd-ca
        use_common_name_for_san: false
        basic_constraints_critical: true
        basic_constraints: "CA:TRUE"
        key_usage_critical: true
        key_usage:
          - digitalSignature
          - keyEncipherment
          - keyCertSign

    - name: ETCD | Generate a Self Signed OpenSSL CA certificate
      openssl_certificate:
        path: "{{ etcd_cert_dir }}/etcd-ca.pem"
        owner: "{{ etcd_user }}"
        group: "{{ etcd_group }}"
        privatekey_path: "{{ etcd_cert_dir }}/etcd-ca-key.pem"
        csr_path: "{{ etcd_cert_dir }}/etcd-ca.csr"
        provider: selfsigned
      notify: ETCD | Set 'etcd_ca_changed' to true
  when: cert_provider == 'ssl'
