---
- name: ETCD | Add member to etcd cluster # noqa 305
  shell: "{{ etcd_bin_path }}/etcdctl member add {{ etcd_member_name }} --peer-urls={{ etcd_peer_url }}"
  register: member_add_result
  changed_when: "'added to cluster' in member_add_result.stdout"
  until: member_add_result.rc == 0
  retries: "4"
  delay: "3"
  environment:
    ETCDCTL_API: 3
    ETCDCTL_CERT: "{{ etcd_cert_dir }}/healthcheck-client.pem"
    ETCDCTL_KEY: "{{ etcd_cert_dir }}/healthcheck-client-key.pem"
    ETCDCTL_CACERT: "{{ etcd_cert_dir }}/etcd-ca.pem"
    ETCDCTL_ENDPOINTS: "{{ etcd_access_addresses }}"

- name: ETCD | Ensure member is in etcd cluster # noqa 306
  shell: "{{ etcd_bin_path }}/etcdctl member list | grep -q {{ etcd_access_address }}"
  register: etcd_member_in_cluster
  changed_when: false
  check_mode: no
  tags:
    - facts
  environment:
    ETCDCTL_API: 3
    ETCDCTL_CERT: "{{ etcd_cert_dir }}/healthcheck-client.pem"
    ETCDCTL_KEY: "{{ etcd_cert_dir }}/healthcheck-client-key.pem"
    ETCDCTL_CACERT: "{{ etcd_cert_dir }}/etcd-ca.pem"
    ETCDCTL_ENDPOINTS: "{{ etcd_access_addresses }}"

# Убеждаемся что ETCD сервис запущен и добавлен в автозапуск
- name: ETCD | Ensure ETCD is started and enabled at boot
  import_tasks: start_native.yml
