---
- name: ETCD | Importing common task - "Getting facts"
  import_tasks: "common/getting_facts.yml"
  tags:
    - facts_task

- name: ETCD | Importing common task - "Creating system user"
  import_tasks: "common/creating_system_user.yml"
  tags:
    - system_user_task

- name: ETCD | Importing common task - "Installing python modules"
  import_tasks: "common/installing_python_modules.yml"
  tags:
    - python_modules_task

- name: ETCD | Importing ETCD installation task
  include_tasks: "{{ etcd_distribution_type }}/installing.yml"
  tags:
    - install_task

- name: ETCD | Importing ETCD configuration task
  include_tasks: "{{ etcd_distribution_type }}/configuring.yml"
  tags:
    - configure_task
