---
- name: ETCD | Slurp ETCD CA certs
  slurp:
    src: "{{ item }}"
  loop:
    - "{{ etcd_cert_dir }}/etcd-ca.pem"
    - "{{ etcd_cert_dir }}/etcd-ca-key.pem"
  register: etcd_ca_certs
  delegate_to: "{{ groups['etcd'][0] }}"
  run_once: true

- name: ETCD | Write out ETCD CA certs
  copy:
    dest: "{{ item.item }}"
    content: "{{ item.content | b64decode }}"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    mode: "0600"
  no_log: true
  register: etcd_ca
  loop: "{{ etcd_ca_certs.results }}"
  when: inventory_hostname != groups['etcd'][0]

# Запускаем принудительное исполнение handlers
- name: ETCD | Flush handlers
  meta: flush_handlers
