---
- name: ETCD | Creating folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ etcd_user_name }}"
    group: "{{ etcd_user_group }}"
    mode: u+rwx
  when:
    - "item is defined"
    - "item | length > 0"
  loop:
    - "{{ etcd_conf_dir }}"
    - "{{ etcd_cert_dir }}"
    - "{{ etcd_data_dir }}"
    - "{{ etcd_wal_dir }}"

- name: ETCD | Generatinf ETCD CA certs
  include_tasks: "pki/{{ cert_provider }}_generating_ca_certs.yml"
  args:
    apply:
      delegate_to: "{{ groups[etcd_group_name][0] }}"
  run_once: true

- name: ETCD | Synchronize ETCD CA certs
  import_tasks: "pki/syncing_ca_certs.yml"

- name: ETCD | Generate server certs
  include_tasks: "pki/{{ cert_provider }}_generating_server_certs.yml"

- name: ETCD | Generate peer certs
  include_tasks: "pki/{{ cert_provider }}_generating_peer_certs.yml"

- name: ETCD | Generate helthcheck certs
  include_tasks: "pki/{{ cert_provider }}_generating_helthcheck_certs.yml"

- name: ETCD | Check if etcd cluster is healthy
  shell: "set -o pipefail && {{ etcd_bin_path }}/etcdctl endpoint --cluster status && {{ etcd_bin_path }}/etcdctl endpoint --cluster health  2>&1 | grep -v 'Error: unhealthy cluster'"
  args:
    executable: /bin/bash
  register: etcd_cluster_is_healthy
  failed_when: false
  changed_when: false
  check_mode: false
  run_once: true
  tags:
    - facts
  environment:
    ETCDCTL_API: 3
    ETCDCTL_CERT: "{{ etcd_client_cert_file }}"
    ETCDCTL_KEY: "{{ etcd_client_key_file }}"
    ETCDCTL_CACERT: "{{ etcd_ca_cert_file }}"
    ETCDCTL_ENDPOINTS: "{{ etcd_endpoints }}"

- name: ETCD | Creating etcd.service file
  template:
    src: "etcd_{{ etcd_distribution_type }}.service.j2"
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: "0644"
  register: etcd_systemd_file

- name: ETCD | Creating etcd.env file
  template:
    src: "etcd.env.j2"
    dest: "{{ etcd_conf_dir }}/etcd.env"
    owner: "{{ etcd_user_name }}"
    group: "{{ etcd_user_group }}"
    mode: "0644"
    backup: true
  register: etcd_config_file

- name: ETCD | Restart etcd
  import_tasks: restarting.yml
  when:
    - "'etcd.service' in services"
    - etcd_config_file.changed or
      etcd_systemd_file.changed or
      etcd_peer_cert.changed or
      etcd_server_cert.changed

- name: ETCD | Ensure ETCD is started and enabled at boot
  import_tasks: starting.yml
  ignore_errors: "{{ etcd_cluster_is_healthy.rc == 0 }}"

- name: ETCD | Wait for etcd cluster to be healthy
  shell: "set -o pipefail && {{ etcd_bin_path }}/etcdctl endpoint --cluster status && {{ etcd_bin_path }}/etcdctl endpoint --cluster health  2>&1 | grep -v 'Error: unhealthy cluster'"
  args:
    executable: /bin/bash
  register: etcd_cluster_is_healthy
  until: etcd_cluster_is_healthy.rc == 0
  retries: "4"
  delay: "3"
  ignore_errors: false
  changed_when: false
  check_mode: false
  run_once: true
  tags:
    - facts
  environment:
    ETCDCTL_API: 3
    ETCDCTL_CERT: "{{ etcd_client_cert_file }}"
    ETCDCTL_KEY: "{{ etcd_client_key_file }}"
    ETCDCTL_CACERT: "{{ etcd_ca_cert_file }}"
    ETCDCTL_ENDPOINTS: "{{ etcd_endpoints }}"

- name: ETCD | Creating etcd.env file
  template:
    src: "etcd.env.j2"
    dest: "{{ etcd_conf_dir }}/etcd.env"
    owner: "{{ etcd_user_name }}"
    group: "{{ etcd_user_group }}"
    mode: "0644"
    backup: true
  register: etcd_config_file

- name: ETCD | Restart etcd
  import_tasks: restarting.yml
  when: etcd_config_file.changed

- name: ETCD | Check if member is in etcd cluster
  shell: "set -o pipefail && {{ etcd_bin_path }}/etcdctl member list | grep {{ etcd_private_address }}"
  args:
    executable: /bin/bash
  register: etcd_member_in_cluster
  ignore_errors: true
  changed_when: false
  check_mode: false
  tags:
    - facts
  environment:
    ETCDCTL_API: 3
    ETCDCTL_CERT: "{{ etcd_client_cert_file }}"
    ETCDCTL_KEY: "{{ etcd_client_key_file }}"
    ETCDCTL_CACERT: "{{ etcd_ca_cert_file }}"
    ETCDCTL_ENDPOINTS: "{{ etcd_endpoints }}"

- name: ETCD | Debug
  debug:
    msg: |
      Server - {{ inventory_hostname }}
      The cluster member? - {{ etcd_member_in_cluster.rc }}
      The cluster is helthy? - {{ etcd_cluster_is_healthy.rc }}
  loop: "{{ groups[etcd_group_name] }}"
  when:
    - inventory_hostname == item

- name: ETCD | Join member(s) to etcd cluster one at a time
  include_tasks: join_etcd_member.yml
  loop: "{{ groups[etcd_group_name] }}"
  when:
    - inventory_hostname == item
    - etcd_member_in_cluster.rc != 0
    - etcd_cluster_is_healthy.rc == 0

- debug:
    var: etcd_endpoints
