---
- name: ETCD | Check etcd binary exists
  stat:
    path: "{{ etcd_bin_path }}/{{ item }}"
    checksum_algorithm: "{{ etcd[etcd_version].checksum_algorithm }}"
  register: etcd_bin
  loop: "{{ etcd_bin_name }}"

- name: ETCD | Set 'install_etcd' to true
  set_fact:
    install_etcd: true
  loop: "{{ etcd_bin.results }}"
  when: item.stat.checksum|default() != etcd[etcd_version][item.item].checksum

- name: ETCD |(when install_etcd == TRUE)
  block:
    - name: ETCD | Creating folders
      file:
        path: "{{ distribution_path }}"
        state: directory
        owner: root
        group: root
        mode: u+rwx

    - name: ETCD | Check that the etcd archive exists on the destination host
      stat:
        path: "{{ distribution_path }}/{{ etcd[etcd_version].source_url | basename }}"
        checksum_algorithm: "{{ etcd[etcd_version].checksum_algorithm }}"
      register: etcd_archive
  when: install_etcd|default(false)

- name: ETCD |(when use_downloader == TRUE)
  block:
    - name: ETCD | Creating default folder for components
      file:
        path: "{{ downloader_source_folder }}"
        state: directory
        mode: u+rwx
      run_once: true
      delegate_to: localhost

    - name: ETCD | Check that the etcd archive exists on the localhost
      stat:
        path: "{{ downloader_source_folder }}/{{ etcd[etcd_version].source_url | basename }}"
        checksum_algorithm: "{{ etcd[etcd_version].checksum_algorithm }}"
      register: downloader_distr
      delegate_to: localhost

    - name: ETCD | Download etcd archive to localhost
      get_url:
        url: "{{ etcd[etcd_version].source_url }}"
        dest: "{{ downloader_source_folder }}"
        checksum: "{{ etcd[etcd_version].checksum_algorithm }}:{{ etcd[etcd_version].archive_checksum }}"
      run_once: true
      delegate_to: localhost
      when: downloader_distr.stat.checksum|default() != etcd[etcd_version].archive_checksum

    - name: ETCD | Copy from localhost to remote host
      copy:
        src: "{{ downloader_source_folder }}/{{ etcd[etcd_version].source_url | basename }}"
        dest: "{{ distribution_path }}"
        owner: root
        group: root
        mode: u+rwx
  when:
    - install_etcd|default(false)
    - use_downloader
    - etcd_archive.stat.checksum|default() != etcd[etcd_version].archive_checksum

- name: ETCD | Download etcd archive to host
  get_url:
    url: "{{ etcd[etcd_version].source_url }}"
    dest: "{{ distribution_path }}"
    checksum: "{{ etcd[etcd_version].checksum_algorithm }}:{{ etcd[etcd_version].archive_checksum }}"
    owner: root
    group: root
  when:
    - install_etcd|default(false)
    - not use_downloader
    - etcd_archive.stat.checksum|default() != etcd[etcd_version].archive_checksum

- name: ETCD | Ensure service is stopped
  service:
    name: etcd
    state: stopped
  when:
    - install_etcd|default(false)
    - "'etcd.service' in services"

- name: ETCD | Extract etcd archive into {{ etcd_bin_path }}
  unarchive:
    src: "{{ distribution_path }}/{{ etcd[etcd_version].source_url | basename }}"
    dest: "{{ etcd_bin_path }}"
    owner: "{{ etcd_user_name }}"
    group: "{{ etcd_user_group }}"
    remote_src: true
    extra_opts: "{{ etcd[etcd_version].extra_opts }}"
  when: install_etcd|default(false)
