---
- name: ETCD | Loading platform variables
  include_vars: "{{ ansible_distribution | lower }}.yml"
  tags:
    - facts
    - python_modules

- name: ETCD | Install the packages (when ansible_python.version.major|int == 2)
  block:
    - name: ETCD | Print platform variables
      debug:
        msg: "Python modules = {{ etcd_required_packages.python2 }}"
      tags:
        - facts

    - name: ETCD | Install the packages
      apt:
        name: "{{ etcd_required_packages.python2 }}"
        update_cache: true
        state: present
      when:
        - ansible_distribution | lower in ['ubuntu','debian']

    - name: ETCD | Install the packages
      yum:
        name: "{{ etcd_required_packages.python2 }}"
        update_cache: true
        state: present
      when:
        - ansible_distribution | lower in ['redhat','centos']

    - name: ETCD | Install the packages
      apt_rpm:
        name: "{{ etcd_required_packages.python2 | join(', ') }}"
        update_cache: true
        state: present
      when:
        - ansible_distribution | lower in ['altlinux']
  when:
    - cert_provider == 'ssl'
    - ansible_python.version.major|int == 2
  tags:
    - python_modules

- name: ETCD | Install the packages (when ansible_python.version.major|int == 3)
  block:
    - name: ETCD | Print platform variables
      debug:
        msg: "Python modules = {{ etcd_required_packages.python3 }}"
      tags:
        - facts

    - name: ETCD | Install the packages
      apt:
        name: "{{ etcd_required_packages.python3 }}"
        update_cache: true
        state: present
      when:
        - ansible_distribution | lower in ['ubuntu','debian']

    - name: ETCD | Install the packages
      yum:
        name: "{{ etcd_required_packages.python3 }}"
        update_cache: true
        state: present
      when:
        - ansible_distribution | lower in ['redhat','centos']

    - name: ETCD | Install the packages
      apt_rpm:
        name: "{{ etcd_required_packages.python3 | join(', ') }}"
        update_cache: true
        state: present
      when:
        - ansible_distribution | lower in ['altlinux']
  when:
    - cert_provider == 'ssl'
    - ansible_python.version.major|int == 3
  tags:
    - python_modules
